version: "3.7"

networks:
    husky:
        name: "husky"

services:
    osrm:
        build:
            context: ./dockerfiles
            dockerfile: DockerfileOSRM
            args:
                OSRM_FILE_NAME: ${OSRM_FILE_NAME}
                OSRM_FILE: ${OSRM_FILE}
        env_file: 
            - ./dockerfiles/.env
        image: osrm:latest
        container_name: osrm
        command: osrm-routed --max-table-size=${MAX_JOBS} --max-viaroute-size=${MAX_JOBS} --algorithm=MLD ${OSRM_FILE_NAME}.osrm
        restart: always
        deploy:
            resources:
                limits:
                    memory: 20G
        ports:
            - "${OSRM_PORT}:5000"
        networks:
            - husky

    vroom:
        build:
            context: ./dockerfiles
            dockerfile: DockerfileVROOM
            args:
                VROOM_SSH_USER: ${VROOM_SSH_USER}
                VROOM_SSH_PASSWORD: ${VROOM_SSH_PASSWORD}
        env_file: 
            - ./dockerfiles/.env
        image: vroom:latest
        container_name: vroom
        command: /usr/sbin/sshd -D
        restart: always
        deploy:
            resources:
                limits:
                    cpus: "7"
                    memory: 20G
        ports:
            - "${VROOM_PORT}:22"
        depends_on:
            - osrm
        networks:
            - husky

    mongo:
        image: mongo
        restart: always
        container_name: mongo
        ports:
            - 6000
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root

    mongo-express:
        image: mongo-express
        restart: always
        container_name: mongo-admin
        ports:
            - 7000:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: root

    api:
        build:
            context: ./dockerfiles
            dockerfile: DockerfileAPI
            args:
                API_GIT: ${API_GIT}
        env_file: 
            - ./dockerfiles/.env
        image: api:latest
        container_name: api
        command: npm start
        restart: always
        deploy:
            resources:
                limits:
                    cpus: "1"
                    memory: 20G
        ports:
            - "${API_PORT}:3000"
        depends_on:
            - osrm
        networks:
            - husky