version: "3.7"

services: 
    osrm:
        build: 
            context: ./dockerfiles
            dockerfile: DockerfileOSRM
        image: osrm:latest
        command: osrm-routed --algorithm=MLD brazil.osrm 
        restart: always
        ports: 
            - "5000:5000"
        networks: 
            - husky

    vroom:
        build: 
            context: ./dockerfiles
            dockerfile: DockerfileVROOM
        image: vroom:latest
        networks: 
            - husky

    vroomAPI:
        build: 
            context: ./dockerfiles
            dockerfile: DockerfileVROOMAPI
        image: vroomAPI:latest
        command: npm start
        restart: always
        ports: 
            - "3000:3000"
        networks: 
            - husky