version: "3.7"

networks:
    husky:
        name: "husky"

services:
    osrm:
        build:
            context: ./dockerfiles
            dockerfile: DockerfileOSRM
        image: osrm:latest
        container_name: osrm
        command: osrm-routed --max-table-size=100000 --max-viaroute-size=100000 --algorithm=MLD brazil-latest.osrm
        restart: always
        cpu_count: 8
        cpu_percent: 90
        cpus: 8
        mem_limit: 20g
        ports:
            - "5000:5000"
        networks:
            - husky

    vroom:
        build:
            context: ./dockerfiles
            dockerfile: DockerfileVROOM
        image: vroom:latest
        container_name: vroom
        command: node vroom-express/src/index.js
        restart: always
        cpu_count: 8
        cpu_percent: 90
        cpus: 8
        mem_limit: 20g
        ports:
            - "3000:3000"
        depends_on:
            - osrm
        networks:
            - husky