version: "3.7"

networks:
    husky:
        name: "husky"

services:
    osrm:
        build:
            context: ./dockerfiles
            dockerfile: DockerfileOSRM
        image: osrm:latest
        container_name: osrm
        command: osrm-routed --max-table-size=100000 --max-viaroute-size=100000 --shared-memory=yes --threads=7 --algorithm=MLD brazil-latest.osrm
        restart: always
        deploy:
            resources:
                limits:
                    memory: 20G
        ports:
            - "5000:5000"
        networks:
            - husky

    vroom:
        build:
            context: ./dockerfiles
            dockerfile: DockerfileVROOM
        image: vroom:latest
        container_name: vroom
        command: /usr/sbin/sshd -D
        restart: always
        deploy:
            resources:
                limits:
                    cpus: "7"
                    memory: 20G
        ports:
            - "4000:22"
        depends_on:
            - osrm
        networks:
            - husky

    api:
        build:
            context: ./dockerfiles
            dockerfile: DockerfileAPI
        image: api:latest
        container_name: api
        command: npm start
        restart: always
        deploy:
            resources:
                limits:
                    cpus: "1"
                    memory: 20G
        ports:
            - "3000:3000"
        depends_on:
            - osrm
        networks:
            - husky