version: "3.7"

networks: 
    husky:
        name: "husky"

volumes: 
    - /bin

services: 
    osrm:
        build: 
            context: ./dockerfiles
            dockerfile: DockerfileOSRM
        image: osrm:latest
        command: osrm-routed --algorithm=MLD brazil-latest.osrm 
        restart: always
        ports: 
            - "5000:5000"
        networks: 
            - husky

    vroom:
        build: 
            context: ./dockerfiles
            dockerfile: DockerfileVROOM
        image: vroom:latest
        restart: always
        depends_on: 
            - osrm
        networks: 
            - husky
        volumes: 
            - "/bin/vroom"

    vroomAPI:
        build: 
            context: ./dockerfiles
            dockerfile: DockerfileVROOMAPI
        image: api:latest
        restart: always
        command: npm start
        depends_on: 
            - vroom
        ports: 
            - "80:3000"
        networks: 
            - husky
        volumes: 
            - "/bin/vroom"